### ISSUE TITLE
Not able to create static resource for xml2js

### ISSUE THREAD

**Issue by Nishitsuthar** [surajp/npm-to-lwc#2]
Hi @surajp I am trying to install xml2js library to create static reasource for my project sinse I couldn't find exact lib file for xml2js.
but I am facing this error 

> opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'

can you please provide your help to understand what's the exact issue is?

**Comment by surajp** [comment]
try setting the environment variable as shown below

`export NODE_OPTIONS=--openssl-legacy-provider`

[source](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported)

**Comment by Nishitsuthar** [comment]
it worked!! thanks @surajp
